<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 4.7.4
 */

/**
 * Database `engurish`
 */

/* `engurish`.`tempo_verbal` */
$tempo_verbal = array(
  array('id' => '1','infinitivo' => 'To be','passado' => 'Was/Were','participio' => 'Been','traducao' => 'Ser/estar','categoria' => 'Verbo'),
  array('id' => '2','infinitivo' => 'To have','passado' => 'Had','participio' => 'Had','traducao' => 'Ter','categoria' => 'Verbo'),
  array('id' => '3','infinitivo' => 'To say','passado' => 'Said','participio' => 'Said','traducao' => 'Dizer','categoria' => 'Verbo'),
  array('id' => '4','infinitivo' => 'To read','passado' => 'Read','participio' => 'Read','traducao' => 'Ler','categoria' => 'Verbo'),
  array('id' => '6','infinitivo' => 'To arise','passado' => 'Arose','participio' => 'Arisen','traducao' => 'Surgir, Elevar-se','categoria' => 'Verbo'),
  array('id' => '7','infinitivo' => 'To awake','passado' => 'Awoke / Awaked','participio' => 'Awoke / Awaked','traducao' => 'Acordar, Despertar','categoria' => 'Verbo'),
  array('id' => '8','infinitivo' => 'To bear','passado' => 'Bore','participio' => 'Born','traducao' => 'Suportar, Dar à luz','categoria' => 'Verbo'),
  array('id' => '9','infinitivo' => 'To beat','passado' => 'Beat','participio' => 'Beaten','traducao' => 'Bater, Vencer, Pulsar','categoria' => 'Verbo'),
  array('id' => '10','infinitivo' => 'To become','passado' => 'Became','participio' => 'Become','traducao' => 'Tornar-se, Virar','categoria' => 'Verbo'),
  array('id' => '11','infinitivo' => 'To begin','passado' => 'Began','participio' => 'Begun','traducao' => 'Começar, Iniciar','categoria' => 'Verbo'),
  array('id' => '12','infinitivo' => 'To bend','passado' => 'Bent','participio' => 'Bent','traducao' => 'Curvar, Dobrar-se','categoria' => 'Verbo'),
  array('id' => '13','infinitivo' => 'To bet','passado' => 'Bet','participio' => 'Bet','traducao' => 'Apostar','categoria' => 'Verbo'),
  array('id' => '14','infinitivo' => 'To Bite','passado' => 'Bit','participio' => 'Bitten','traducao' => 'Morder, Picar','categoria' => 'Verbo'),
  array('id' => '15','infinitivo' => 'To bleed','passado' => 'Bled','participio' => 'Bled','traducao' => 'Sangrar','categoria' => 'Verbo'),
  array('id' => '16','infinitivo' => 'To Blow','passado' => 'Blew','participio' => 'Blown','traducao' => 'Soprar','categoria' => 'Verbo'),
  array('id' => '17','infinitivo' => 'To Break','passado' => 'Broke','participio' => 'Broken','traducao' => 'Quebrar, Partir','categoria' => 'Verbo'),
  array('id' => '18','infinitivo' => 'To breed','passado' => 'Bred','participio' => 'Bred','traducao' => 'Criar, Educar','categoria' => 'Verbo'),
  array('id' => '19','infinitivo' => 'To Bring','passado' => 'Brought','participio' => 'Brought','traducao' => 'Trazer','categoria' => 'Verbo'),
  array('id' => '20','infinitivo' => 'To build','passado' => 'Built','participio' => 'Built','traducao' => 'Construir, Edificar','categoria' => 'Verbo'),
  array('id' => '21','infinitivo' => 'To burn','passado' => 'Burnt / Burned','participio' => 'Burnt / Burned','traducao' => 'Queimar','categoria' => 'Verbo'),
  array('id' => '22','infinitivo' => 'To burst','passado' => 'Burst','participio' => 'Burst','traducao' => 'Arrebentar, Estourar','categoria' => 'Verbo'),
  array('id' => '23','infinitivo' => 'To buy','passado' => 'Bought','participio' => 'Bought','traducao' => 'Comprar','categoria' => 'Verbo'),
  array('id' => '24','infinitivo' => 'To cast','passado' => 'Cast','participio' => 'Cast','traducao' => 'Lançar, Atirar','categoria' => 'Verbo'),
  array('id' => '25','infinitivo' => 'To catch','passado' => 'Caught','participio' => 'Caught','traducao' => 'Pegar, Prender','categoria' => 'Verbo'),
  array('id' => '26','infinitivo' => 'To choose','passado' => 'Chose','participio' => 'Chosen','traducao' => 'Escolher','categoria' => 'Verbo'),
  array('id' => '27','infinitivo' => 'To come','passado' => 'Came','participio' => 'Came','traducao' => 'Vir','categoria' => 'Verbo'),
  array('id' => '28','infinitivo' => 'To cost','passado' => 'Cost','participio' => 'Cost','traducao' => 'Custar','categoria' => 'Verbo'),
  array('id' => '29','infinitivo' => 'To creep','passado' => 'Crept','participio' => 'Crept','traducao' => 'Deslizar-se, Rastejar','categoria' => 'Verbo'),
  array('id' => '30','infinitivo' => 'To cut','passado' => 'Cut','participio' => 'Cut','traducao' => 'Cortar','categoria' => 'Verbo'),
  array('id' => '31','infinitivo' => 'To deal','passado' => 'Dealt','participio' => 'Dealt','traducao' => 'Lidar (com)','categoria' => 'Verbo'),
  array('id' => '32','infinitivo' => 'To dig','passado' => 'Dug','participio' => 'Dug','traducao' => 'Cavar','categoria' => 'Verbo'),
  array('id' => '33','infinitivo' => 'To do','passado' => 'Did','participio' => 'Done','traducao' => 'Fazer','categoria' => 'Verbo'),
  array('id' => '34','infinitivo' => 'To draw','passado' => 'Drew','participio' => 'Drawn','traducao' => 'Desenhar, Puxar, Sacar','categoria' => 'Verbo'),
  array('id' => '35','infinitivo' => 'To dream','passado' => 'Dreamt / Dreamed','participio' => 'Dreamt / Dreamed','traducao' => 'Sonhar','categoria' => 'Verbo'),
  array('id' => '36','infinitivo' => 'To Drink','passado' => 'Drank','participio' => 'Drunk','traducao' => 'Beber','categoria' => 'Verbo'),
  array('id' => '37','infinitivo' => 'To drive','passado' => 'Drove','participio' => 'Driven','traducao' => 'Dirigir','categoria' => 'Verbo'),
  array('id' => '38','infinitivo' => 'To dwell','passado' => 'Dwelt','participio' => 'Dwelt','traducao' => 'Morar','categoria' => 'Verbo'),
  array('id' => '39','infinitivo' => 'To eat','passado' => 'Ate','participio' => 'Eaten','traducao' => 'Comer','categoria' => 'Verbo'),
  array('id' => '40','infinitivo' => 'To fall','passado' => 'Fell','participio' => 'Fallen','traducao' => 'Cair','categoria' => 'Verbo'),
  array('id' => '41','infinitivo' => 'To feed','passado' => 'Fed','participio' => 'Fed','traducao' => 'Alimentar','categoria' => 'Verbo'),
  array('id' => '42','infinitivo' => 'To fight','passado' => 'Fought','participio' => 'Fought','traducao' => 'Lutar, Combater','categoria' => 'Verbo'),
  array('id' => '43','infinitivo' => 'To find','passado' => 'Found','participio' => 'Found','traducao' => 'Achar, Encontrar','categoria' => 'Verbo'),
  array('id' => '44','infinitivo' => 'To flee','passado' => 'Fled','participio' => 'Fled','traducao' => 'Fugir (de), Escapar','categoria' => 'Verbo'),
  array('id' => '45','infinitivo' => 'To fly','passado' => 'Flew','participio' => 'Flown','traducao' => 'Voar','categoria' => 'Verbo'),
  array('id' => '46','infinitivo' => 'To get','passado' => 'Got','participio' => 'Got / Gotten','traducao' => 'Conseguir, Ganhar, Obter','categoria' => 'Verbo'),
  array('id' => '47','infinitivo' => 'To Give','passado' => 'Gave','participio' => 'Given','traducao' => 'Dar','categoria' => 'Verbo'),
  array('id' => '48','infinitivo' => 'To go','passado' => 'Went','participio' => 'Gone','traducao' => 'Ir','categoria' => 'Verbo'),
  array('id' => '49','infinitivo' => 'To Grind','passado' => 'Ground','participio' => 'Ground','traducao' => 'Moer, Pulverizar','categoria' => 'Verbo'),
  array('id' => '50','infinitivo' => 'To grow','passado' => 'Grew','participio' => 'Grown','traducao' => 'Crescer, Cultivar, Ficar','categoria' => 'Verbo'),
  array('id' => '51','infinitivo' => 'To hang','passado' => 'Hung / Hanged','participio' => 'Hung / Hanged','traducao' => 'Pendurar, Enforcar','categoria' => 'Verbo'),
  array('id' => '52','infinitivo' => 'To hear','passado' => 'Heard','participio' => 'Heard','traducao' => 'Ouvir','categoria' => 'Verbo'),
  array('id' => '53','infinitivo' => 'To hide','passado' => 'Hid','participio' => 'Hidden','traducao' => 'Esconder','categoria' => 'Verbo'),
  array('id' => '54','infinitivo' => 'To hit','passado' => 'Hit','participio' => 'Hit','traducao' => 'Bater','categoria' => 'Verbo'),
  array('id' => '55','infinitivo' => 'To Hold','passado' => 'Held','participio' => 'Held','traducao' => 'Segurar, Conter, Manter','categoria' => 'Verbo'),
  array('id' => '56','infinitivo' => 'To hurt','passado' => 'Hurt','participio' => 'Hurt','traducao' => 'Ferir, Doer, Machucar','categoria' => 'Verbo'),
  array('id' => '57','infinitivo' => 'To keep','passado' => 'Kept','participio' => 'Kept','traducao' => 'Conservar, Manter, Guardar','categoria' => 'Verbo'),
  array('id' => '58','infinitivo' => 'To Kneel','passado' => 'Knelt','participio' => 'Knelt','traducao' => 'Ajoelhar-se','categoria' => 'Verbo'),
  array('id' => '59','infinitivo' => 'To Know','passado' => 'Knew','participio' => 'Knew','traducao' => 'Saber, Conhecer','categoria' => 'Verbo'),
  array('id' => '60','infinitivo' => 'To lay','passado' => 'Laid','participio' => 'Laid','traducao' => 'Pôr','categoria' => 'Verbo'),
  array('id' => '61','infinitivo' => 'To lead','passado' => 'Led','participio' => 'Led','traducao' => 'Conduzir, Liderar','categoria' => 'Verbo'),
  array('id' => '62','infinitivo' => 'To lean','passado' => 'Leant / Leaned','participio' => 'Leant / Leaned','traducao' => 'Inclinar-se','categoria' => 'Verbo'),
  array('id' => '63','infinitivo' => 'To leap','passado' => 'Leapt / Leaped','participio' => 'Leapt / Leaped','traducao' => 'Saltar','categoria' => 'Verbo'),
  array('id' => '64','infinitivo' => 'To learn','passado' => 'learnt / learned','participio' => 'learnt / learned','traducao' => 'Aprender','categoria' => 'Verbo'),
  array('id' => '65','infinitivo' => 'To leave','passado' => 'Left','participio' => 'Left','traducao' => 'Deixar, Partir, Sair','categoria' => 'Verbo'),
  array('id' => '66','infinitivo' => 'To lend','passado' => 'Lent','participio' => 'Lent','traducao' => 'Emprestar','categoria' => 'Verbo'),
  array('id' => '67','infinitivo' => 'To let','passado' => 'Let','participio' => 'Let','traducao' => 'Deixar, Permitir','categoria' => 'Verbo'),
  array('id' => '68','infinitivo' => 'To lie','passado' => 'Lay','participio' => 'Lain','traducao' => 'Deitar-se, Jazer, Situar-se','categoria' => 'Verbo'),
  array('id' => '69','infinitivo' => 'To light','passado' => 'Lit / Lighted','participio' => 'Lit / Lighted','traducao' => 'Acender, Iluminar','categoria' => 'Verbo'),
  array('id' => '70','infinitivo' => 'To lose','passado' => 'Lost','participio' => 'Lost','traducao' => 'Perder','categoria' => 'Verbo'),
  array('id' => '71','infinitivo' => 'To make','passado' => 'Made','participio' => 'Made','traducao' => 'Fazer, Fabricar','categoria' => 'Verbo'),
  array('id' => '72','infinitivo' => 'To mean','passado' => 'Meant','participio' => 'Meant','traducao' => 'Significar, Querer dizer','categoria' => 'Verbo'),
  array('id' => '73','infinitivo' => 'To meet','passado' => 'Met','participio' => 'Met','traducao' => 'Encontrar(se)','categoria' => 'Verbo'),
  array('id' => '74','infinitivo' => 'To pay','passado' => 'Paid','participio' => 'Paid','traducao' => 'Pagar','categoria' => 'Verbo'),
  array('id' => '75','infinitivo' => 'To put','passado' => 'Put','participio' => 'Put','traducao' => 'Pôr, Colocar','categoria' => 'Verbo'),
  array('id' => '76','infinitivo' => 'To quit','passado' => 'Quit / Quitted','participio' => 'Quit / Quitted','traducao' => 'Deixar / Abandonar','categoria' => 'Verbo'),
  array('id' => '77','infinitivo' => 'To read','passado' => 'Read','participio' => 'Read','traducao' => 'Ler','categoria' => 'Verbo'),
  array('id' => '78','infinitivo' => 'To ride','passado' => 'Rode','participio' => 'Ridden','traducao' => 'Cavalgar, Passear','categoria' => 'Verbo'),
  array('id' => '79','infinitivo' => 'To Ring','passado' => 'Rang','participio' => 'Rung','traducao' => 'Soar, Tocar, Repicar','categoria' => 'Verbo'),
  array('id' => '80','infinitivo' => 'To run','passado' => 'Ran','participio' => 'Run','traducao' => 'Correr','categoria' => 'Verbo'),
  array('id' => '81','infinitivo' => 'To say','passado' => 'Said','participio' => 'Said','traducao' => 'Dizer','categoria' => 'Verbo'),
  array('id' => '82','infinitivo' => 'To see','passado' => 'Saw','participio' => 'Seen','traducao' => 'Ver','categoria' => 'Verbo'),
  array('id' => '83','infinitivo' => 'To seek','passado' => 'Sought','participio' => 'Sought','traducao' => 'Buscar, Procurar','categoria' => 'Verbo'),
  array('id' => '84','infinitivo' => 'To sell','passado' => 'Sold','participio' => 'Sold','traducao' => 'Vender','categoria' => 'Verbo'),
  array('id' => '85','infinitivo' => 'To Send','passado' => 'Sent','participio' => 'Sent','traducao' => 'Enviar, Mandar','categoria' => 'Verbo'),
  array('id' => '86','infinitivo' => 'To set','passado' => 'Set','participio' => 'Set','traducao' => 'Pôr, Fixar','categoria' => 'Verbo'),
  array('id' => '87','infinitivo' => 'To shake','passado' => 'Shook','participio' => 'Shaken','traducao' => 'Sacudir, Agitar','categoria' => 'Verbo'),
  array('id' => '88','infinitivo' => 'To shed','passado' => 'Shed','participio' => 'Shed','traducao' => 'Derramar','categoria' => 'Verbo'),
  array('id' => '89','infinitivo' => 'To shine','passado' => 'Shone','participio' => 'Shone','traducao' => 'Brilhar, Polir','categoria' => 'Verbo'),
  array('id' => '90','infinitivo' => 'To shoot','passado' => 'Shot','participio' => 'Shot','traducao' => 'Atirar, Fuzilar','categoria' => 'Verbo'),
  array('id' => '91','infinitivo' => 'To show','passado' => 'Showed','participio' => 'Shown','traducao' => 'Mostrar','categoria' => 'Verbo'),
  array('id' => '92','infinitivo' => 'To shrink','passado' => 'Shrank','participio' => 'Shrunk','traducao' => 'Encolher (se)','categoria' => 'Verbo'),
  array('id' => '93','infinitivo' => 'To shut','passado' => 'Shut','participio' => 'Shut','traducao' => 'Fechar','categoria' => 'Verbo'),
  array('id' => '94','infinitivo' => 'To sing','passado' => 'Sang','participio' => 'Sung','traducao' => 'Cantar','categoria' => 'Verbo'),
  array('id' => '95','infinitivo' => 'To sink','passado' => 'Sank','participio' => 'Sunk','traducao' => 'Afundar','categoria' => 'Verbo'),
  array('id' => '96','infinitivo' => 'To sit','passado' => 'Sat','participio' => 'Sat','traducao' => 'Sentar (se)','categoria' => 'Verbo'),
  array('id' => '97','infinitivo' => 'To slay','passado' => 'Slew','participio' => 'Slain','traducao' => 'Matar, Destruir','categoria' => 'Verbo'),
  array('id' => '98','infinitivo' => 'To sleep','passado' => 'Slept','participio' => 'Slept','traducao' => 'Dormir','categoria' => 'Verbo'),
  array('id' => '99','infinitivo' => 'To slide','passado' => 'Slid','participio' => 'Slid','traducao' => 'Deslizar, Escorregar','categoria' => 'Verbo'),
  array('id' => '100','infinitivo' => 'To smell','passado' => 'Smelt / Smelled','participio' => 'Smelt / Smelled','traducao' => 'Cheirar','categoria' => 'Verbo'),
  array('id' => '101','infinitivo' => 'To speak','passado' => 'Spoke','participio' => 'Spoken','traducao' => 'Falar','categoria' => 'Verbo'),
  array('id' => '102','infinitivo' => 'To spell','passado' => 'Spelt / Spelled','participio' => 'Spelt / Spelled','traducao' => 'Gravar / Soletrar','categoria' => 'Verbo'),
  array('id' => '103','infinitivo' => 'To spend','passado' => 'Spent','participio' => 'Spent','traducao' => 'Gastar, Passar','categoria' => 'Verbo'),
  array('id' => '104','infinitivo' => 'To spill','passado' => 'Spilt / Spilled','participio' => 'Spilt / Spilled','traducao' => 'Entornar, Derramar','categoria' => 'Verbo'),
  array('id' => '105','infinitivo' => 'To spoil','passado' => 'Spoilt / Spoiled','participio' => 'Spoilt / Spoiled','traducao' => 'Estragar','categoria' => 'Verbo'),
  array('id' => '106','infinitivo' => 'To spread','passado' => 'Spread','participio' => 'Spread','traducao' => 'Espalhar (se)','categoria' => 'Verbo'),
  array('id' => '107','infinitivo' => 'To stand','passado' => 'Stood','participio' => 'Stood','traducao' => 'Ficar de pé, Suportar','categoria' => 'Verbo'),
  array('id' => '108','infinitivo' => 'To steal','passado' => 'Stole','participio' => 'Stolen','traducao' => 'Roubar','categoria' => 'Verbo'),
  array('id' => '109','infinitivo' => 'To stick','passado' => 'Stuck','participio' => 'Stuck','traducao' => 'Fincar, Espetar, Fixar','categoria' => 'Verbo'),
  array('id' => '110','infinitivo' => 'To strike','passado' => 'Struck','participio' => 'Struck / Stricken','traducao' => 'Bater, Golpear','categoria' => 'Verbo'),
  array('id' => '111','infinitivo' => 'To swear','passado' => 'Swore','participio' => 'Sworn','traducao' => 'Jurar','categoria' => 'Verbo'),
  array('id' => '112','infinitivo' => 'To sweep','passado' => 'Swept','participio' => 'Swept','traducao' => 'Varrer','categoria' => 'Verbo'),
  array('id' => '113','infinitivo' => 'To Swin','passado' => 'Swan','participio' => 'Swum','traducao' => 'Nadar','categoria' => 'Verbo'),
  array('id' => '114','infinitivo' => 'To swing','passado' => 'Swung','participio' => 'Swung','traducao' => 'Balançar','categoria' => 'Verbo'),
  array('id' => '115','infinitivo' => 'To take','passado' => 'Took','participio' => 'Taken','traducao' => 'Tomar, Pegar, Levar','categoria' => 'Verbo'),
  array('id' => '116','infinitivo' => 'To teach','passado' => 'Taught','participio' => 'Taught','traducao' => 'Ensinar','categoria' => 'Verbo'),
  array('id' => '117','infinitivo' => 'To tear','passado' => 'Tore','participio' => 'Torn','traducao' => 'Rasgar (se)','categoria' => 'Verbo'),
  array('id' => '118','infinitivo' => 'To tell','passado' => 'Told','participio' => 'Told','traducao' => 'Dizer, Contar','categoria' => 'Verbo'),
  array('id' => '119','infinitivo' => 'To think','passado' => 'Thought','participio' => 'Thought','traducao' => 'Pensar, Achar','categoria' => 'Verbo'),
  array('id' => '120','infinitivo' => 'To throw','passado' => 'Threw','participio' => 'Thrown','traducao' => 'Arremessar, Atirar','categoria' => 'Verbo'),
  array('id' => '121','infinitivo' => 'To understand','passado' => 'Understood','participio' => 'Understood','traducao' => 'Compreender, Entender','categoria' => 'Verbo'),
  array('id' => '122','infinitivo' => 'To upset','passado' => 'Upset','participio' => 'Upset','traducao' => 'Perturbar, Preocupar','categoria' => 'Verbo'),
  array('id' => '123','infinitivo' => 'To wake','passado' => 'Woke / Waked','participio' => 'Woken / Waked','traducao' => 'Acordar, Despertar','categoria' => 'Verbo'),
  array('id' => '124','infinitivo' => 'To wear','passado' => 'Wore','participio' => 'Worn','traducao' => 'Usar, Vestir','categoria' => 'Verbo'),
  array('id' => '125','infinitivo' => 'To weep','passado' => 'Wept','participio' => 'Wept','traducao' => 'Chorar','categoria' => 'Verbo'),
  array('id' => '126','infinitivo' => 'To win','passado' => 'Won','participio' => 'Won','traducao' => 'Ganhar, Vencer','categoria' => 'Verbo'),
  array('id' => '127','infinitivo' => 'To wind','passado' => 'Wound','participio' => 'Wound','traducao' => 'Enrolar (se), Envolver','categoria' => 'Verbo'),
  array('id' => '128','infinitivo' => 'To write','passado' => 'Wrote','participio' => 'Written','traducao' => 'Escrever','categoria' => 'Verbo')
);

/* `engurish`.`traducao` */
$traducao = array(
  array('id' => '28','palavra' => 'Answer','traducao' => 'Atender, Resposta','categoria' => 'False cognate words'),
  array('id' => '26','palavra' => 'Warn','traducao' => 'Avisar','categoria' => 'False cognate words'),
  array('id' => '27','palavra' => 'Attend','traducao' => 'Assistir a, Frequentar','categoria' => 'False cognate words'),
  array('id' => '24','palavra' => 'At present','traducao' => 'Atualmente, Presentemente','categoria' => 'False cognate words'),
  array('id' => '21','palavra' => 'Actual','traducao' => 'Real','categoria' => 'False cognate words'),
  array('id' => '25','palavra' => 'Advice','traducao' => 'Aconselhar','categoria' => 'False cognate words'),
  array('id' => '22','palavra' => 'Present','traducao' => 'Atual','categoria' => 'False cognate words'),
  array('id' => '23','palavra' => 'Actually','traducao' => 'Realmente','categoria' => 'False cognate words'),
  array('id' => '29','palavra' => 'Cigar','traducao' => 'Charuto','categoria' => 'False cognate words'),
  array('id' => '30','palavra' => 'Cigarette','traducao' => 'Cigarro','categoria' => 'False cognate words'),
  array('id' => '31','palavra' => 'Beef','traducao' => 'Carne de Boi','categoria' => 'False cognate words'),
  array('id' => '32','palavra' => 'Steak','traducao' => 'Bife','categoria' => 'False cognate words'),
  array('id' => '33','palavra' => 'College','traducao' => 'Faculdade','categoria' => 'False cognate words'),
  array('id' => '34','palavra' => 'High School','traducao' => 'Colégio (Ensino Médio)','categoria' => 'False cognate words'),
  array('id' => '35','palavra' => 'Comprehensive','traducao' => 'Completo','categoria' => 'False cognate words'),
  array('id' => '36','palavra' => 'Understanding','traducao' => 'Compreensivo','categoria' => 'False cognate words'),
  array('id' => '37','palavra' => 'Costume','traducao' => 'Fantasia (roupa)','categoria' => 'False cognate words'),
  array('id' => '38','palavra' => 'Custom, Habit','traducao' => 'Costume','categoria' => 'False cognate words'),
  array('id' => '39','palavra' => 'Deception','traducao' => 'Engano, Fraude','categoria' => 'False cognate words'),
  array('id' => '40','palavra' => 'Disappointment','traducao' => 'Decepção','categoria' => 'False cognate words'),
  array('id' => '41','palavra' => 'Estate','traducao' => 'Bens Imobiliários','categoria' => 'False cognate words'),
  array('id' => '42','palavra' => 'State','traducao' => 'Estado','categoria' => 'False cognate words'),
  array('id' => '43','palavra' => 'Eventually','traducao' => 'Finalmente','categoria' => 'False cognate words'),
  array('id' => '44','palavra' => 'Casually','traducao' => 'Eventualmente','categoria' => 'False cognate words'),
  array('id' => '45','palavra' => 'Exit','traducao' => 'Saída','categoria' => 'False cognate words'),
  array('id' => '46','palavra' => 'Success','traducao' => 'Êxito','categoria' => 'False cognate words'),
  array('id' => '47','palavra' => 'Expert','traducao' => 'Perito, Especialista','categoria' => 'False cognate words'),
  array('id' => '48','palavra' => 'Smart','traducao' => 'Esperto','categoria' => 'False cognate words'),
  array('id' => '49','palavra' => 'Exquisite','traducao' => 'Refinado, Requintado','categoria' => 'False cognate words'),
  array('id' => '50','palavra' => 'Odd, Strange','traducao' => 'Esquisito','categoria' => 'False cognate words'),
  array('id' => '51','palavra' => 'Fabric','traducao' => 'Pano, Tecido','categoria' => 'False cognate words'),
  array('id' => '52','palavra' => 'Factory','traducao' => 'Fábrica','categoria' => 'False cognate words'),
  array('id' => '53','palavra' => 'Injury','traducao' => 'Ferida','categoria' => 'False cognate words'),
  array('id' => '54','palavra' => 'Insult','traducao' => 'Injúria','categoria' => 'False cognate words'),
  array('id' => '55','palavra' => 'Ingenious','traducao' => 'Criativo','categoria' => 'False cognate words'),
  array('id' => '56','palavra' => 'Naive','traducao' => 'Ingênuo','categoria' => 'False cognate words'),
  array('id' => '57','palavra' => 'Large','traducao' => 'Grande','categoria' => 'False cognate words'),
  array('id' => '58','palavra' => 'Wide','traducao' => 'Largo','categoria' => 'False cognate words'),
  array('id' => '59','palavra' => 'Lecture','traducao' => 'Conferência, Aula','categoria' => 'False cognate words'),
  array('id' => '60','palavra' => 'Reading','traducao' => 'Leitura','categoria' => 'False cognate words'),
  array('id' => '61','palavra' => 'Library','traducao' => 'Biblioteca','categoria' => 'False cognate words'),
  array('id' => '62','palavra' => 'Bookshop, Bookstore','traducao' => 'Livraria','categoria' => 'False cognate words'),
  array('id' => '63','palavra' => 'Liquor','traducao' => 'Bebida Alcólica','categoria' => 'False cognate words'),
  array('id' => '64','palavra' => 'Liqueur','traducao' => 'Licor','categoria' => 'False cognate words'),
  array('id' => '65','palavra' => 'Mayor','traducao' => 'Prefeito','categoria' => 'False cognate words'),
  array('id' => '66','palavra' => 'Bigger, Greater','traducao' => 'Maior','categoria' => 'False cognate words'),
  array('id' => '67','palavra' => 'Morose','traducao' => 'Taciturno, Rabujeto','categoria' => 'False cognate words'),
  array('id' => '68','palavra' => 'Slow','traducao' => 'Moroso, Devagar','categoria' => 'False cognate words'),
  array('id' => '69','palavra' => 'Novel','traducao' => 'Romance','categoria' => 'False cognate words'),
  array('id' => '70','palavra' => 'Romance, Soap, Ópera','traducao' => 'Novela','categoria' => 'False cognate words'),
  array('id' => '71','palavra' => 'Ordinary','traducao' => 'Comum','categoria' => 'False cognate words'),
  array('id' => '72','palavra' => 'Low, Vulgar','traducao' => 'Ordinário','categoria' => 'False cognate words'),
  array('id' => '73','palavra' => 'Ore','traducao' => 'Minério','categoria' => 'False cognate words'),
  array('id' => '74','palavra' => 'Gold','traducao' => 'Ouro','categoria' => 'False cognate words'),
  array('id' => '75','palavra' => 'Parents','traducao' => 'Pais','categoria' => 'False cognate words'),
  array('id' => '76','palavra' => 'Relatives','traducao' => 'Parentes','categoria' => 'False cognate words'),
  array('id' => '77','palavra' => 'Particular','traducao' => 'Específica','categoria' => 'False cognate words'),
  array('id' => '78','palavra' => 'Private','traducao' => 'Particular','categoria' => 'False cognate words'),
  array('id' => '79','palavra' => 'Petrol','traducao' => 'Gasolina','categoria' => 'False cognate words'),
  array('id' => '80','palavra' => 'Petroleum','traducao' => 'Petróleo','categoria' => 'False cognate words'),
  array('id' => '81','palavra' => 'Prejudice','traducao' => 'Preconceito','categoria' => 'False cognate words'),
  array('id' => '82','palavra' => 'Damage','traducao' => 'Prejuízo','categoria' => 'False cognate words'),
  array('id' => '83','palavra' => 'Presently','traducao' => 'Em Breve','categoria' => 'False cognate words'),
  array('id' => '84','palavra' => 'Policy','traducao' => 'Linha de Ação (política)','categoria' => 'False cognate words'),
  array('id' => '85','palavra' => 'Police','traducao' => 'Polícia','categoria' => 'False cognate words'),
  array('id' => '86','palavra' => 'Pork','traducao' => 'Carne de Porco','categoria' => 'False cognate words'),
  array('id' => '87','palavra' => 'Pig','traducao' => 'Porco','categoria' => 'False cognate words'),
  array('id' => '88','palavra' => 'Pretend','traducao' => 'Fingir','categoria' => 'False cognate words'),
  array('id' => '89','palavra' => 'To intend','traducao' => 'Pretender','categoria' => 'False cognate words'),
  array('id' => '90','palavra' => 'Push','traducao' => 'Empurrar','categoria' => 'False cognate words'),
  array('id' => '91','palavra' => 'Pull','traducao' => 'Puxar','categoria' => 'False cognate words'),
  array('id' => '92','palavra' => 'Realize','traducao' => 'Perceber','categoria' => 'False cognate words'),
  array('id' => '93','palavra' => 'Carry out','traducao' => 'Realizar','categoria' => 'False cognate words'),
  array('id' => '94','palavra' => 'Scholar','traducao' => 'Erudito','categoria' => 'False cognate words'),
  array('id' => '95','palavra' => 'Schoolboy','traducao' => 'Escolar','categoria' => 'False cognate words'),
  array('id' => '96','palavra' => 'Sensible','traducao' => 'Sensato','categoria' => 'False cognate words'),
  array('id' => '97','palavra' => 'Sensitive','traducao' => 'Sensível','categoria' => 'False cognate words'),
  array('id' => '98','palavra' => 'Silicon','traducao' => 'Silício','categoria' => 'False cognate words'),
  array('id' => '99','palavra' => 'Silicone','traducao' => 'Silicone','categoria' => 'False cognate words'),
  array('id' => '100','palavra' => 'Sort','traducao' => 'Tipo','categoria' => 'False cognate words'),
  array('id' => '101','palavra' => 'Luck','traducao' => 'Sorte','categoria' => 'False cognate words'),
  array('id' => '102','palavra' => 'Stranger','traducao' => 'Estranho','categoria' => 'False cognate words'),
  array('id' => '103','palavra' => 'Foreigner','traducao' => 'Estrangeiro','categoria' => 'False cognate words'),
  array('id' => '104','palavra' => 'Support','traducao' => 'Apoiar','categoria' => 'False cognate words'),
  array('id' => '105','palavra' => 'Bear, Stand','traducao' => 'Suportar','categoria' => 'False cognate words'),
  array('id' => '106','palavra' => 'Tenant','traducao' => 'Inquilino','categoria' => 'False cognate words'),
  array('id' => '107','palavra' => 'Lieutenant','traducao' => 'Tenente','categoria' => 'False cognate words'),
  array('id' => '108','palavra' => 'Bring','traducao' => 'Trazer','categoria' => 'Phrasal verbs'),
  array('id' => '109','palavra' => 'Bring about','traducao' => 'Causar','categoria' => 'Phrasal verbs'),
  array('id' => '110','palavra' => 'Bring back','traducao' => 'Devolver','categoria' => 'Phrasal verbs'),
  array('id' => '111','palavra' => 'Bring in','traducao' => 'Introduzir','categoria' => 'Phrasal verbs'),
  array('id' => '112','palavra' => 'Bring up','traducao' => 'Educar','categoria' => 'Phrasal verbs'),
  array('id' => '113','palavra' => 'Call','traducao' => 'Chamar','categoria' => 'Phrasal verbs'),
  array('id' => '114','palavra' => 'Call down','traducao' => 'Repreender (severamente)','categoria' => 'Phrasal verbs'),
  array('id' => '115','palavra' => 'Call for','traducao' => 'Demandar, Requerer, Ir buscar','categoria' => 'Phrasal verbs'),
  array('id' => '116','palavra' => 'Call off','traducao' => 'Cancelar','categoria' => 'Phrasal verbs'),
  array('id' => '117','palavra' => 'Call up','traducao' => 'Telefonar','categoria' => 'Phrasal verbs'),
  array('id' => '118','palavra' => 'Come','traducao' => 'Vir','categoria' => 'Phrasal verbs'),
  array('id' => '119','palavra' => 'Come about','traducao' => 'Acontecer','categoria' => 'Phrasal verbs'),
  array('id' => '120','palavra' => 'Come across','traducao' => 'Encontrar por acaso','categoria' => 'Phrasal verbs'),
  array('id' => '121','palavra' => 'Come along','traducao' => 'Acompanhar, Apressar-se','categoria' => 'Phrasal verbs'),
  array('id' => '122','palavra' => 'Come back','traducao' => 'Voltar','categoria' => 'Phrasal verbs'),
  array('id' => '123','palavra' => 'Come from','traducao' => 'Vir de','categoria' => 'Phrasal verbs'),
  array('id' => '124','palavra' => 'Come out','traducao' => 'Aparecer','categoria' => 'Phrasal verbs'),
  array('id' => '125','palavra' => 'Come through','traducao' => 'Sobreviver','categoria' => 'Phrasal verbs'),
  array('id' => '126','palavra' => 'Come up','traducao' => 'Acontecer','categoria' => 'Phrasal verbs'),
  array('id' => '127','palavra' => 'Cut','traducao' => 'Cortar','categoria' => 'Phrasal verbs'),
  array('id' => '128','palavra' => 'Cut down','traducao' => 'Derrubar','categoria' => 'Phrasal verbs'),
  array('id' => '129','palavra' => 'Cut down on','traducao' => 'Reduzir','categoria' => 'Phrasal verbs'),
  array('id' => '130','palavra' => 'Cut off','traducao' => 'Desligar','categoria' => 'Phrasal verbs'),
  array('id' => '131','palavra' => 'Cut out','traducao' => 'Eliminar','categoria' => 'Phrasal verbs'),
  array('id' => '132','palavra' => 'Cut up','traducao' => 'Cortar em Pedações','categoria' => 'Phrasal verbs'),
  array('id' => '133','palavra' => 'Get','traducao' => 'Ganhar, Obter, Conseguir','categoria' => 'Phrasal verbs'),
  array('id' => '134','palavra' => 'Get along','traducao' => 'Progredir','categoria' => 'Phrasal verbs'),
  array('id' => '135','palavra' => 'Get along with','traducao' => 'Relacionar-se','categoria' => 'Phrasal verbs'),
  array('id' => '136','palavra' => 'Get away','traducao' => 'Escapar','categoria' => 'Phrasal verbs'),
  array('id' => '137','palavra' => 'Get back','traducao' => 'Voltar','categoria' => 'Phrasal verbs'),
  array('id' => '138','palavra' => 'Get down','traducao' => 'Descer','categoria' => 'Phrasal verbs'),
  array('id' => '139','palavra' => 'Get off','traducao' => 'Descer','categoria' => 'Phrasal verbs'),
  array('id' => '140','palavra' => 'Get out','traducao' => 'Sair','categoria' => 'Phrasal verbs'),
  array('id' => '141','palavra' => 'Get over','traducao' => 'Recuperar-se','categoria' => 'Phrasal verbs'),
  array('id' => '142','palavra' => 'Get throught with','traducao' => 'Terminar completamente','categoria' => 'Phrasal verbs'),
  array('id' => '143','palavra' => 'Get up','traducao' => 'Levantar-se','categoria' => 'Phrasal verbs'),
  array('id' => '144','palavra' => 'Give','traducao' => 'Dar','categoria' => 'Phrasal verbs'),
  array('id' => '145','palavra' => 'Give away','traducao' => 'Distribuir/Trair','categoria' => 'Phrasal verbs'),
  array('id' => '146','palavra' => 'Give back','traducao' => 'Devolver','categoria' => 'Phrasal verbs'),
  array('id' => '147','palavra' => 'Give in','traducao' => 'Render-se','categoria' => 'Phrasal verbs'),
  array('id' => '148','palavra' => 'Give out','traducao' => 'Acabar, Terminar','categoria' => 'Phrasal verbs'),
  array('id' => '149','palavra' => 'Give up','traducao' => 'Desistir, Abandonar, Renunciar','categoria' => 'Phrasal verbs'),
  array('id' => '150','palavra' => 'Go','traducao' => 'Ir','categoria' => 'Phrasal verbs'),
  array('id' => '151','palavra' => 'Go away','traducao' => 'Ir embora','categoria' => 'Phrasal verbs'),
  array('id' => '152','palavra' => 'Go back','traducao' => 'Voltar','categoria' => 'Phrasal verbs'),
  array('id' => '153','palavra' => 'Go by','traducao' => 'Passar (por)','categoria' => 'Phrasal verbs'),
  array('id' => '154','palavra' => 'Go down','traducao' => 'Descer','categoria' => 'Phrasal verbs'),
  array('id' => '155','palavra' => 'Go off','traducao' => 'Partir, Explodir','categoria' => 'Phrasal verbs'),
  array('id' => '156','palavra' => 'Go on','traducao' => 'Acontecer, Continuar','categoria' => 'Phrasal verbs'),
  array('id' => '157','palavra' => 'Go out','traducao' => 'Sair','categoria' => 'Phrasal verbs'),
  array('id' => '158','palavra' => 'Go through','traducao' => 'Sofrer (dificuldades, desconforto etc)','categoria' => 'Phrasal verbs'),
  array('id' => '159','palavra' => 'Go up','traducao' => 'Subir','categoria' => 'Phrasal verbs'),
  array('id' => '160','palavra' => 'Look','traducao' => 'Olhar, Parecer','categoria' => 'Phrasal verbs'),
  array('id' => '161','palavra' => 'Look after','traducao' => 'Cuidar de','categoria' => 'Phrasal verbs'),
  array('id' => '162','palavra' => 'Look at','traducao' => 'Olhar para examinar','categoria' => 'Phrasal verbs'),
  array('id' => '163','palavra' => 'Look down on','traducao' => 'Desprezar','categoria' => 'Phrasal verbs'),
  array('id' => '164','palavra' => 'Look for','traducao' => 'Procurar','categoria' => 'Phrasal verbs'),
  array('id' => '165','palavra' => 'Look foward to','traducao' => 'Ansiar por','categoria' => 'Phrasal verbs'),
  array('id' => '166','palavra' => 'Look into','traducao' => 'Investigar','categoria' => 'Phrasal verbs'),
  array('id' => '167','palavra' => 'Look out','traducao' => 'Ter cuidado','categoria' => 'Phrasal verbs'),
  array('id' => '168','palavra' => 'Look over','traducao' => 'Examinar cuidadosamente','categoria' => 'Phrasal verbs'),
  array('id' => '169','palavra' => 'Look up to','traducao' => 'Admirar, Respeitar','categoria' => 'Phrasal verbs'),
  array('id' => '170','palavra' => 'Make','traducao' => 'Fazer','categoria' => 'Phrasal verbs'),
  array('id' => '171','palavra' => 'Make off','traducao' => 'Escapar','categoria' => 'Phrasal verbs'),
  array('id' => '172','palavra' => 'Make out','traducao' => 'Entender','categoria' => 'Phrasal verbs'),
  array('id' => '173','palavra' => 'Make up','traducao' => 'Formar, Compor, Constituir / Fazer as pazes, Inventar, Aplicar cosméticos (em)','categoria' => 'Phrasal verbs'),
  array('id' => '174','palavra' => 'Make up one´s mind','traducao' => 'Chegar a uma conclusão','categoria' => 'Phrasal verbs'),
  array('id' => '175','palavra' => 'Make up for','traducao' => 'Compensar por','categoria' => 'Phrasal verbs'),
  array('id' => '176','palavra' => 'Put','traducao' => 'Colocar','categoria' => 'Phrasal verbs'),
  array('id' => '177','palavra' => 'Put across','traducao' => 'Comunicar-se com sucesso','categoria' => 'Phrasal verbs'),
  array('id' => '178','palavra' => 'Put away','traducao' => 'Guardar','categoria' => 'Phrasal verbs'),
  array('id' => '179','palavra' => 'Put on','traducao' => 'Vestir','categoria' => 'Phrasal verbs'),
  array('id' => '180','palavra' => 'Put off','traducao' => 'Adiar','categoria' => 'Phrasal verbs'),
  array('id' => '181','palavra' => 'Put out','traducao' => 'Apagar','categoria' => 'Phrasal verbs'),
  array('id' => '182','palavra' => 'Put up with','traducao' => 'Tolerar','categoria' => 'Phrasal verbs'),
  array('id' => '183','palavra' => 'Take','traducao' => 'Levar, Pegar','categoria' => 'Phrasal verbs'),
  array('id' => '184','palavra' => 'Take after','traducao' => 'Parecer-se','categoria' => 'Phrasal verbs'),
  array('id' => '185','palavra' => 'Take away','traducao' => 'Remover','categoria' => 'Phrasal verbs'),
  array('id' => '186','palavra' => 'Take back','traducao' => 'Devolver','categoria' => 'Phrasal verbs'),
  array('id' => '187','palavra' => 'Take in','traducao' => 'Receber alguém em casa / Enganar','categoria' => 'Phrasal verbs'),
  array('id' => '188','palavra' => 'Take over','traducao' => 'Assumir o controle','categoria' => 'Phrasal verbs'),
  array('id' => '189','palavra' => 'Take to (up)','traducao' => 'Adquirir um hábito','categoria' => 'Phrasal verbs'),
  array('id' => '190','palavra' => 'Turn','traducao' => 'Virar','categoria' => 'Phrasal verbs'),
  array('id' => '191','palavra' => 'Turn away','traducao' => 'Rejeitar','categoria' => 'Phrasal verbs'),
  array('id' => '192','palavra' => 'Turn down','traducao' => 'Recusar, Rejeitar','categoria' => 'Phrasal verbs'),
  array('id' => '193','palavra' => 'Turn in','traducao' => 'Ir dormir','categoria' => 'Phrasal verbs'),
  array('id' => '194','palavra' => 'Turn off','traducao' => 'Desligar','categoria' => 'Phrasal verbs'),
  array('id' => '195','palavra' => 'Turn on','traducao' => 'Ligar','categoria' => 'Phrasal verbs'),
  array('id' => '196','palavra' => 'Turn out','traducao' => 'Desligar / Resultar','categoria' => 'Phrasal verbs'),
  array('id' => '197','palavra' => 'Turn over','traducao' => 'Virar','categoria' => 'Phrasal verbs'),
  array('id' => '198','palavra' => 'Turn to','traducao' => 'Pedir ajuda','categoria' => 'Phrasal verbs'),
  array('id' => '199','palavra' => 'Turn up','traducao' => 'Aparecer','categoria' => 'Phrasal verbs'),
  array('id' => '200','palavra' => 'Aboard','traducao' => 'A bordo','categoria' => 'Preposition'),
  array('id' => '201','palavra' => 'About','traducao' => 'Sobre, A respeito de, Cerca de','categoria' => 'Preposition'),
  array('id' => '202','palavra' => 'Above','traducao' => 'Sobre, Por sobre, Mais de, Superior a','categoria' => 'Preposition'),
  array('id' => '203','palavra' => 'Across','traducao' => 'Através de, Do outro lado','categoria' => 'Preposition'),
  array('id' => '204','palavra' => 'After','traducao' => 'Depois, Após, Atrás de','categoria' => 'Preposition'),
  array('id' => '205','palavra' => 'Against','traducao' => 'Contra, De encontro a, Diante, Contrário, Em oposição a, Em comparação a','categoria' => 'Preposition'),
  array('id' => '206','palavra' => 'Ahead of','traducao' => 'À frente de','categoria' => 'Preposition'),
  array('id' => '207','palavra' => 'Along','traducao' => 'Ao longo de, junto a, ao lado de, paralelo a','categoria' => 'Preposition'),
  array('id' => '208','palavra' => 'Amid','traducao' => 'Entre, No meio de','categoria' => 'Preposition'),
  array('id' => '209','palavra' => 'Amidst','traducao' => 'No meio','categoria' => 'Preposition'),
  array('id' => '210','palavra' => 'Among','traducao' => 'Entre, No meio de','categoria' => 'Preposition'),
  array('id' => '211','palavra' => 'Around','traducao' => 'Ao redor de, Perto de, por','categoria' => 'Preposition'),
  array('id' => '212','palavra' => 'As','traducao' => 'Como, Tão, Na qualidade de','categoria' => 'Preposition'),
  array('id' => '213','palavra' => 'As far as','traducao' => 'Tão longe quanto','categoria' => 'Preposition'),
  array('id' => '214','palavra' => 'As of','traducao' => 'A partir de','categoria' => 'Preposition'),
  array('id' => '215','palavra' => 'Aside from','traducao' => 'Além de','categoria' => 'Preposition'),
  array('id' => '216','palavra' => 'At','traducao' => 'Em, À, No','categoria' => 'Preposition'),
  array('id' => '217','palavra' => 'Barring','traducao' => 'Salvo por, Exceto','categoria' => 'Preposition'),
  array('id' => '218','palavra' => 'Because of','traducao' => 'Por causa de','categoria' => 'Preposition'),
  array('id' => '219','palavra' => 'Behind','traducao' => 'Atrás de, Detrás de, Depois de (traseiro como substantivo)','categoria' => 'Preposition'),
  array('id' => '220','palavra' => 'Before','traducao' => 'Diante, Em frente de, Antes de','categoria' => 'Preposition'),
  array('id' => '221','palavra' => 'Below','traducao' => 'Abaixo de, Para baixo','categoria' => 'Preposition'),
  array('id' => '222','palavra' => 'Beneath','traducao' => 'Abaixo, Sob, Inferior a','categoria' => 'Preposition'),
  array('id' => '223','palavra' => 'Beside','traducao' => 'Ao lado de','categoria' => 'Preposition'),
  array('id' => '224','palavra' => 'Besides','traducao' => 'Além de','categoria' => 'Preposition'),
  array('id' => '225','palavra' => 'Between','traducao' => 'Entre','categoria' => 'Preposition'),
  array('id' => '226','palavra' => 'Beyond','traducao' => 'Além de, Fora do alcance, Mais longe que','categoria' => 'Preposition'),
  array('id' => '227','palavra' => 'But','traducao' => 'Mas','categoria' => 'Preposition'),
  array('id' => '228','palavra' => 'By','traducao' => 'Por, Perto de, De, Cerca de','categoria' => 'Preposition'),
  array('id' => '229','palavra' => 'Circa','traducao' => 'Cerca de, Aproximadamente (Precedidos de uma data)','categoria' => 'Preposition'),
  array('id' => '230','palavra' => 'Concerning','traducao' => 'Em relação a, A respeito de','categoria' => 'Preposition'),
  array('id' => '231','palavra' => 'Despite','traducao' => 'Apesar de, Não obstante','categoria' => 'Preposition'),
  array('id' => '232','palavra' => 'Down','traducao' => 'Abaixo','categoria' => 'Preposition'),
  array('id' => '233','palavra' => 'During','traducao' => 'Durante','categoria' => 'Preposition'),
  array('id' => '234','palavra' => 'Except','traducao' => 'Exceto','categoria' => 'Preposition'),
  array('id' => '235','palavra' => 'Except for','traducao' => 'Exceto por','categoria' => 'Preposition'),
  array('id' => '236','palavra' => 'Far from','traducao' => 'Longe de','categoria' => 'Preposition'),
  array('id' => '237','palavra' => 'Following','traducao' => 'Seguindo (vindo depois ou como um resultado de)','categoria' => 'Preposition'),
  array('id' => '238','palavra' => 'For','traducao' => 'Para, Durante, Devido a','categoria' => 'Preposition'),
  array('id' => '239','palavra' => 'From','traducao' => 'De, Desde','categoria' => 'Preposition'),
  array('id' => '240','palavra' => 'In','traducao' => 'Em, Dentro de, No meio de, A, De, Com, Para','categoria' => 'Preposition'),
  array('id' => '241','palavra' => 'In case of','traducao' => 'Em caso de','categoria' => 'Preposition'),
  array('id' => '242','palavra' => 'In front of','traducao' => 'Em frente de','categoria' => 'Preposition'),
  array('id' => '243','palavra' => 'In place of','traducao' => 'No lugar de','categoria' => 'Preposition'),
  array('id' => '244','palavra' => 'In spite of','traducao' => 'Apesar de, A despeito de, Embora','categoria' => 'Preposition'),
  array('id' => '245','palavra' => 'Spite','traducao' => 'Despeito','categoria' => 'Preposition'),
  array('id' => '246','palavra' => 'Including','traducao' => 'Incluindo','categoria' => 'Preposition'),
  array('id' => '247','palavra' => 'Inside','traducao' => 'Em, Dentro de, Para dentro','categoria' => 'Preposition'),
  array('id' => '248','palavra' => 'Instead of','traducao' => 'Ao invés de','categoria' => 'Preposition'),
  array('id' => '249','palavra' => 'Into','traducao' => 'Para, Em, Para dentro de','categoria' => 'Preposition'),
  array('id' => '250','palavra' => 'Like','traducao' => 'Como','categoria' => 'Preposition'),
  array('id' => '251','palavra' => 'Minus','traducao' => 'Menos, Desprovido, Negativo','categoria' => 'Preposition'),
  array('id' => '252','palavra' => 'Near','traducao' => 'Próximo de, Junto a, A cerca de','categoria' => 'Preposition'),
  array('id' => '253','palavra' => 'Next to','traducao' => 'Ao Lado de','categoria' => 'Preposition'),
  array('id' => '254','palavra' => 'Of','traducao' => 'De, Feito de, A respeito de, Em','categoria' => 'Preposition'),
  array('id' => '255','palavra' => 'Off','traducao' => 'De, Fora de, Para fora','categoria' => 'Preposition'),
  array('id' => '256','palavra' => 'On','traducao' => 'Em, Sobre, Em cima de, A respeito de','categoria' => 'Preposition'),
  array('id' => '257','palavra' => 'On behalf of','traducao' => 'Em nome de','categoria' => 'Preposition'),
  array('id' => '258','palavra' => 'On top of','traducao' => 'Em cima de','categoria' => 'Preposition'),
  array('id' => '259','palavra' => 'Onto','traducao' => 'Para, Para cima de, Em direção a','categoria' => 'Preposition'),
  array('id' => '260','palavra' => 'Opposite','traducao' => 'Oposto, Contra, Em frente de','categoria' => 'Preposition'),
  array('id' => '261','palavra' => 'Out','traducao' => 'Fora','categoria' => 'Preposition'),
  array('id' => '262','palavra' => 'Out of','traducao' => 'Fora de','categoria' => 'Preposition'),
  array('id' => '263','palavra' => 'Outside','traducao' => 'Fora de, Lado de fora','categoria' => 'Preposition'),
  array('id' => '264','palavra' => 'Over','traducao' => 'Sobre, Por sobre, Acima de, Mais de','categoria' => 'Preposition'),
  array('id' => '265','palavra' => 'Past','traducao' => 'Passado, Sem, Fora de','categoria' => 'Preposition'),
  array('id' => '266','palavra' => 'Plus','traducao' => 'Mais, Adicionado a','categoria' => 'Preposition'),
  array('id' => '267','palavra' => 'Prior to','traducao' => 'Antes de, Anteriormente a','categoria' => 'Preposition'),
  array('id' => '268','palavra' => 'Regarding','traducao' => 'A respeito de, Em relação a, Quanto a','categoria' => 'Preposition'),
  array('id' => '269','palavra' => 'Regardless of','traducao' => 'Independentemente de, Não obstante','categoria' => 'Preposition'),
  array('id' => '270','palavra' => 'Round','traducao' => 'Em volta de, Por todo, Em torno','categoria' => 'Preposition'),
  array('id' => '271','palavra' => 'Through','traducao' => 'Através de, Durante, Por, Por causa de, Devido a','categoria' => 'Preposition'),
  array('id' => '272','palavra' => 'Till','traducao' => 'Até','categoria' => 'Preposition'),
  array('id' => '273','palavra' => 'To','traducao' => 'Para, Até, Por, De','categoria' => 'Preposition'),
  array('id' => '274','palavra' => 'Toward(s)','traducao' => 'Em direção de','categoria' => 'Preposition'),
  array('id' => '275','palavra' => 'Under','traducao' => 'Debaixo, Inferior, Por baixo','categoria' => 'Preposition'),
  array('id' => '276','palavra' => 'Underneath','traducao' => 'Por baixo','categoria' => 'Preposition'),
  array('id' => '277','palavra' => 'Unlike','traducao' => 'Ao contrário, Não como, De modo diferente','categoria' => 'Preposition'),
  array('id' => '278','palavra' => 'Until','traducao' => 'Até','categoria' => 'Preposition'),
  array('id' => '279','palavra' => 'Up','traducao' => 'Acima','categoria' => 'Preposition'),
  array('id' => '280','palavra' => 'Upon','traducao' => 'Sobre','categoria' => 'Preposition'),
  array('id' => '281','palavra' => 'Versus','traducao' => 'Contra (rivalidade)','categoria' => 'Preposition'),
  array('id' => '282','palavra' => 'Via','traducao' => 'Via','categoria' => 'Preposition'),
  array('id' => '283','palavra' => 'With','traducao' => 'Com, De, Para, Por','categoria' => 'Preposition'),
  array('id' => '284','palavra' => 'With regard to','traducao' => 'Em relação a','categoria' => 'Preposition'),
  array('id' => '285','palavra' => 'Within','traducao' => 'Dentro de','categoria' => 'Preposition'),
  array('id' => '286','palavra' => 'Without','traducao' => 'Sem, Destituído de','categoria' => 'Preposition'),
  array('id' => '287','palavra' => 'And','traducao' => 'e','categoria' => 'Conjuctions and Connectors'),
  array('id' => '288','palavra' => 'Both... and','traducao' => 'Tanto... quanto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '289','palavra' => 'As well as','traducao' => 'Bem como','categoria' => 'Conjuctions and Connectors'),
  array('id' => '290','palavra' => 'Not only... but also','traducao' => 'Não só... mas também','categoria' => 'Conjuctions and Connectors'),
  array('id' => '291','palavra' => 'Besides','traducao' => 'Além disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '292','palavra' => 'Futhermore','traducao' => 'Além disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '293','palavra' => 'Moreover','traducao' => 'Além disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '294','palavra' => 'Further','traducao' => 'Mais distante','categoria' => 'Conjuctions and Connectors'),
  array('id' => '295','palavra' => 'In addition','traducao' => 'Além do que, Além do mais','categoria' => 'Conjuctions and Connectors'),
  array('id' => '296','palavra' => 'Additionally','traducao' => 'Além disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '297','palavra' => 'Then','traducao' => 'Então','categoria' => 'Conjuctions and Connectors'),
  array('id' => '298','palavra' => 'Also','traducao' => 'Além disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '299','palavra' => 'Too','traducao' => 'Também','categoria' => 'Conjuctions and Connectors'),
  array('id' => '300','palavra' => 'Again','traducao' => 'Novamente, De novo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '301','palavra' => 'Equally important','traducao' => 'Igualmente importante','categoria' => 'Conjuctions and Connectors'),
  array('id' => '302','palavra' => 'First... second','traducao' => 'Primeiro... segundo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '303','palavra' => 'Finally, Last','traducao' => 'Finalmente, Por último','categoria' => 'Conjuctions and Connectors'),
  array('id' => '304','palavra' => 'Or','traducao' => 'Ou','categoria' => 'Conjuctions and Connectors'),
  array('id' => '305','palavra' => 'Either... or','traducao' => 'ou... ou','categoria' => 'Conjuctions and Connectors'),
  array('id' => '306','palavra' => 'Neither... nor','traducao' => 'Nem... nem','categoria' => 'Conjuctions and Connectors'),
  array('id' => '307','palavra' => 'If','traducao' => 'Se','categoria' => 'Conjuctions and Connectors'),
  array('id' => '308','palavra' => 'Unless','traducao' => 'A menos que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '309','palavra' => 'As long as','traducao' => 'Contanto que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '310','palavra' => 'Provided, Providing that','traducao' => 'Contanto que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '311','palavra' => 'Whether','traducao' => 'Se','categoria' => 'Conjuctions and Connectors'),
  array('id' => '312','palavra' => 'So','traducao' => 'Assim','categoria' => 'Conjuctions and Connectors'),
  array('id' => '313','palavra' => 'Thus','traducao' => 'Assim','categoria' => 'Conjuctions and Connectors'),
  array('id' => '314','palavra' => 'Hence','traducao' => 'Portanto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '315','palavra' => 'Therefore','traducao' => 'Portanto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '316','palavra' => 'Accordingly','traducao' => 'Consequentemente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '317','palavra' => 'Consequently','traducao' => 'Consequentemente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '318','palavra' => 'Thereupon','traducao' => 'Então','categoria' => 'Conjuctions and Connectors'),
  array('id' => '319','palavra' => 'As a result','traducao' => 'Como um resultado','categoria' => 'Conjuctions and Connectors'),
  array('id' => '320','palavra' => 'In consequence','traducao' => 'Em consequência ','categoria' => 'Conjuctions and Connectors'),
  array('id' => '321','palavra' => 'So then','traducao' => 'Então','categoria' => 'Conjuctions and Connectors'),
  array('id' => '322','palavra' => 'Though','traducao' => 'Embora','categoria' => 'Conjuctions and Connectors'),
  array('id' => '323','palavra' => 'Although','traducao' => 'Embora','categoria' => 'Conjuctions and Connectors'),
  array('id' => '324','palavra' => 'Even Though','traducao' => 'Muito embora','categoria' => 'Conjuctions and Connectors'),
  array('id' => '325','palavra' => 'Despite, In spite of','traducao' => 'Apesar de','categoria' => 'Conjuctions and Connectors'),
  array('id' => '326','palavra' => 'Regardless of','traducao' => 'Apesar de','categoria' => 'Conjuctions and Connectors'),
  array('id' => '327','palavra' => 'But','traducao' => 'Mas','categoria' => 'Conjuctions and Connectors'),
  array('id' => '328','palavra' => 'Yet','traducao' => 'Contudo, Entretanto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '329','palavra' => 'However','traducao' => 'Contudo, Entretanto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '330','palavra' => 'Nevertheless','traducao' => 'Contudo, Entretanto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '331','palavra' => 'On the other hand','traducao' => 'Por outro lado','categoria' => 'Conjuctions and Connectors'),
  array('id' => '332','palavra' => 'Whereas','traducao' => 'Ao passo que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '333','palavra' => 'On the contrary','traducao' => 'Pelo contrário','categoria' => 'Conjuctions and Connectors'),
  array('id' => '334','palavra' => 'Even so','traducao' => 'Mesmo assim','categoria' => 'Conjuctions and Connectors'),
  array('id' => '335','palavra' => 'Notwithstanding','traducao' => 'A despeito de','categoria' => 'Conjuctions and Connectors'),
  array('id' => '336','palavra' => 'Alternatively','traducao' => 'Alternativamente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '337','palavra' => 'At the same time','traducao' => 'Ao mesmo tempo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '338','palavra' => 'Otherwise','traducao' => 'De outra forma','categoria' => 'Conjuctions and Connectors'),
  array('id' => '339','palavra' => 'Instead','traducao' => 'Em vez de','categoria' => 'Conjuctions and Connectors'),
  array('id' => '340','palavra' => 'Nonetheless','traducao' => 'Não obstante','categoria' => 'Conjuctions and Connectors'),
  array('id' => '341','palavra' => 'Conversely','traducao' => 'De modo inverso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '342','palavra' => 'As','traducao' => 'Como','categoria' => 'Conjuctions and Connectors'),
  array('id' => '343','palavra' => 'As if','traducao' => 'Como se','categoria' => 'Conjuctions and Connectors'),
  array('id' => '344','palavra' => 'As though','traducao' => 'Como se','categoria' => 'Conjuctions and Connectors'),
  array('id' => '345','palavra' => 'So as to','traducao' => 'A fim de','categoria' => 'Conjuctions and Connectors'),
  array('id' => '346','palavra' => 'In order to','traducao' => 'A fim de','categoria' => 'Conjuctions and Connectors'),
  array('id' => '347','palavra' => 'So that','traducao' => 'Para que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '348','palavra' => 'Because','traducao' => 'Porque','categoria' => 'Conjuctions and Connectors'),
  array('id' => '349','palavra' => 'For','traducao' => 'Porque, Para','categoria' => 'Conjuctions and Connectors'),
  array('id' => '350','palavra' => 'Because of this','traducao' => 'Por causa disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '351','palavra' => 'For that reason','traducao' => 'Por esta razão ','categoria' => 'Conjuctions and Connectors'),
  array('id' => '352','palavra' => 'As soon as','traducao' => 'Tão logo que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '353','palavra' => 'When','traducao' => 'Quando','categoria' => 'Conjuctions and Connectors'),
  array('id' => '354','palavra' => 'While','traducao' => 'Enquanto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '355','palavra' => 'Till','traducao' => 'Até que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '356','palavra' => 'Until','traducao' => 'Até que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '357','palavra' => 'In the meantime','traducao' => 'Enquanto isso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '358','palavra' => 'Since','traducao' => 'Desde que','categoria' => 'Conjuctions and Connectors'),
  array('id' => '359','palavra' => 'Meanwhile','traducao' => 'Enquanto isso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '360','palavra' => 'Presently','traducao' => 'Em breve','categoria' => 'Conjuctions and Connectors'),
  array('id' => '361','palavra' => 'At least','traducao' => 'Finalmente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '362','palavra' => 'Finally','traducao' => 'Finalmente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '363','palavra' => 'Immediately','traducao' => 'Imediatamente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '364','palavra' => 'Thereafter','traducao' => 'Depois disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '365','palavra' => 'At that time','traducao' => 'Naquela hora, Naquela ocasião','categoria' => 'Conjuctions and Connectors'),
  array('id' => '366','palavra' => 'Subsequently','traducao' => 'Subsequentemente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '367','palavra' => 'Enventually','traducao' => 'Enventualmente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '368','palavra' => 'Currently','traducao' => 'Atualmente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '369','palavra' => 'In the meantime','traducao' => 'Enquanto isso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '370','palavra' => 'In the past','traducao' => 'No passado','categoria' => 'Conjuctions and Connectors'),
  array('id' => '371','palavra' => 'In the same way','traducao' => 'Do mesmo jeito','categoria' => 'Conjuctions and Connectors'),
  array('id' => '372','palavra' => 'Like','traducao' => 'Como','categoria' => 'Conjuctions and Connectors'),
  array('id' => '373','palavra' => 'Likewise','traducao' => 'Da mesma forma','categoria' => 'Conjuctions and Connectors'),
  array('id' => '374','palavra' => 'Similarly','traducao' => 'Similarmente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '375','palavra' => 'Comparable','traducao' => 'Comparável','categoria' => 'Conjuctions and Connectors'),
  array('id' => '376','palavra' => 'As with','traducao' => 'Como com','categoria' => 'Conjuctions and Connectors'),
  array('id' => '377','palavra' => 'Equality','traducao' => 'Igualdade','categoria' => 'Conjuctions and Connectors'),
  array('id' => '378','palavra' => 'Just as... so too','traducao' => 'Assim como... também','categoria' => 'Conjuctions and Connectors'),
  array('id' => '379','palavra' => 'Another ','traducao' => 'Outro, Mais um','categoria' => 'Conjuctions and Connectors'),
  array('id' => '380','palavra' => 'A similar','traducao' => 'Um similar','categoria' => 'Conjuctions and Connectors'),
  array('id' => '381','palavra' => 'To sum up','traducao' => 'Resumindo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '382','palavra' => 'In summary','traducao' => 'Em suma','categoria' => 'Conjuctions and Connectors'),
  array('id' => '383','palavra' => 'Briefly','traducao' => 'Brevemente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '384','palavra' => 'To conclude','traducao' => 'Concluir','categoria' => 'Conjuctions and Connectors'),
  array('id' => '385','palavra' => 'In a word','traducao' => 'Em uma palavra','categoria' => 'Conjuctions and Connectors'),
  array('id' => '386','palavra' => 'In short','traducao' => 'Em resumo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '387','palavra' => 'On the whole','traducao' => 'No todo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '388','palavra' => 'Whole','traducao' => 'Todo, Integral, Completo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '389','palavra' => 'In other words','traducao' => 'Em outras palavras','categoria' => 'Conjuctions and Connectors'),
  array('id' => '390','palavra' => 'To be sure','traducao' => 'Para ter certeza','categoria' => 'Conjuctions and Connectors'),
  array('id' => '391','palavra' => 'Clearly','traducao' => 'Claramente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '392','palavra' => 'Anyway','traducao' => 'De qualquer maneira, Em todo caso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '393','palavra' => 'In sum','traducao' => 'Em suma','categoria' => 'Conjuctions and Connectors'),
  array('id' => '394','palavra' => 'After all','traducao' => 'Depois de tudo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '395','palavra' => 'In general','traducao' => 'No geral','categoria' => 'Conjuctions and Connectors'),
  array('id' => '396','palavra' => 'It seems','traducao' => 'Parece','categoria' => 'Conjuctions and Connectors'),
  array('id' => '397','palavra' => 'In brief','traducao' => 'Em breve','categoria' => 'Conjuctions and Connectors'),
  array('id' => '398','palavra' => 'Indeed','traducao' => 'De fato','categoria' => 'Conjuctions and Connectors'),
  array('id' => '399','palavra' => 'Certainly','traducao' => 'Certamente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '400','palavra' => 'As a matter of fact','traducao' => 'De fato, Como aliás','categoria' => 'Conjuctions and Connectors'),
  array('id' => '401','palavra' => 'In fact','traducao' => 'De fato','categoria' => 'Conjuctions and Connectors'),
  array('id' => '402','palavra' => 'Actually','traducao' => 'Na Realidade, Efetivamente, Atualmente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '403','palavra' => 'For example','traducao' => 'Por exemplo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '404','palavra' => 'For instance','traducao' => 'Por exemplo','categoria' => 'Conjuctions and Connectors'),
  array('id' => '405','palavra' => 'Namely','traducao' => 'Nomeadamente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '406','palavra' => 'That is (to say)','traducao' => 'Isto é','categoria' => 'Conjuctions and Connectors'),
  array('id' => '407','palavra' => 'Such as','traducao' => 'Tal como','categoria' => 'Conjuctions and Connectors'),
  array('id' => '408','palavra' => 'In other words','traducao' => 'Em outras palavras','categoria' => 'Conjuctions and Connectors'),
  array('id' => '409','palavra' => 'Are revealed by','traducao' => 'São revelados por','categoria' => 'Conjuctions and Connectors'),
  array('id' => '410','palavra' => 'Illustrated by','traducao' => 'Ilustrado por','categoria' => 'Conjuctions and Connectors'),
  array('id' => '411','palavra' => 'Specifically','traducao' => 'Especificamente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '412','palavra' => 'In particular','traducao' => 'Em particular','categoria' => 'Conjuctions and Connectors'),
  array('id' => '413','palavra' => 'For one thing','traducao' => 'Por uma coisa','categoria' => 'Conjuctions and Connectors'),
  array('id' => '414','palavra' => 'This can be seen in','traducao' => 'Estes podem ser vistos em','categoria' => 'Conjuctions and Connectors'),
  array('id' => '415','palavra' => 'In instance of this','traducao' => 'Uma instância disso','categoria' => 'Conjuctions and Connectors'),
  array('id' => '416','palavra' => 'There','traducao' => 'Lá','categoria' => 'Conjuctions and Connectors'),
  array('id' => '417','palavra' => 'Here','traducao' => 'Aqui','categoria' => 'Conjuctions and Connectors'),
  array('id' => '418','palavra' => 'Beyond','traducao' => 'Além, Acolá','categoria' => 'Conjuctions and Connectors'),
  array('id' => '419','palavra' => 'Nearby','traducao' => 'Nas proximidades','categoria' => 'Conjuctions and Connectors'),
  array('id' => '420','palavra' => 'Next to','traducao' => 'Ao lado de','categoria' => 'Conjuctions and Connectors'),
  array('id' => '421','palavra' => 'At that point','traducao' => 'Nesse ponto','categoria' => 'Conjuctions and Connectors'),
  array('id' => '422','palavra' => 'Opposite to','traducao' => 'Oposto a','categoria' => 'Conjuctions and Connectors'),
  array('id' => '423','palavra' => 'Adjacent to','traducao' => 'Adjacente a','categoria' => 'Conjuctions and Connectors'),
  array('id' => '424','palavra' => 'On the other side','traducao' => 'Por outro lado','categoria' => 'Conjuctions and Connectors'),
  array('id' => '425','palavra' => 'In the front','traducao' => 'Na frente','categoria' => 'Conjuctions and Connectors'),
  array('id' => '426','palavra' => 'In the back','traducao' => 'Na volta','categoria' => 'Conjuctions and Connectors'),
  array('id' => '427','palavra' => 'Now','traducao' => 'Agora','categoria' => 'Adverb'),
  array('id' => '428','palavra' => 'Then','traducao' => 'Então, Depois, Em seguida','categoria' => 'Adverb'),
  array('id' => '429','palavra' => 'Soon','traducao' => 'Em breve, Logo','categoria' => 'Adverb'),
  array('id' => '430','palavra' => 'Later','traducao' => 'Mais tarde','categoria' => 'Adverb'),
  array('id' => '431','palavra' => 'Yet','traducao' => 'Ainda, Até o momento','categoria' => 'Adverb'),
  array('id' => '432','palavra' => 'Already','traducao' => 'Já (time)','categoria' => 'Adverb'),
  array('id' => '433','palavra' => 'Tonight','traducao' => 'Esta noite','categoria' => 'Adverb'),
  array('id' => '434','palavra' => 'Last night','traducao' => 'Noite passada','categoria' => 'Adverb'),
  array('id' => '435','palavra' => 'Nearly','traducao' => 'Por pouco','categoria' => 'Adverb'),
  array('id' => '436','palavra' => 'Totally','traducao' => 'Totalmente','categoria' => 'Adverb'),
  array('id' => '437','palavra' => 'Partly','traducao' => 'Em parte, Parcialmente','categoria' => 'Adverb'),
  array('id' => '438','palavra' => 'Enough','traducao' => 'O suficiente','categoria' => 'Adverb'),
  array('id' => '439','palavra' => 'Hardly','traducao' => 'Dificilmente','categoria' => 'Adverb'),
  array('id' => '440','palavra' => 'Really','traducao' => 'Realmente','categoria' => 'Adverb'),
  array('id' => '441','palavra' => 'Mostly','traducao' => 'Na maioria das vezes','categoria' => 'Adverb'),
  array('id' => '442','palavra' => 'A little','traducao' => 'Um pouco','categoria' => 'Adverb'),
  array('id' => '443','palavra' => 'Always','traducao' => 'Sempre','categoria' => 'Adverb'),
  array('id' => '444','palavra' => 'Never','traducao' => 'Nunca','categoria' => 'Adverb'),
  array('id' => '445','palavra' => 'Ever','traducao' => 'Alguma vez','categoria' => 'Adverb'),
  array('id' => '446','palavra' => 'Usually','traducao' => 'Usualmente','categoria' => 'Adverb'),
  array('id' => '447','palavra' => 'Often','traducao' => 'Muitas vezes','categoria' => 'Adverb'),
  array('id' => '448','palavra' => 'Sometimes','traducao' => 'Às vezes','categoria' => 'Adverb'),
  array('id' => '449','palavra' => 'rarely','traducao' => 'Raramente','categoria' => 'Adverb'),
  array('id' => '450','palavra' => 'Hardly ever','traducao' => 'Quase nunca','categoria' => 'Adverb'),
  array('id' => '451','palavra' => 'Clearly','traducao' => 'Claramente','categoria' => 'Adverb'),
  array('id' => '452','palavra' => 'Apparently','traducao' => 'Pelo visto, Aparentemente','categoria' => 'Adverb'),
  array('id' => '453','palavra' => 'Alas','traducao' => 'Infelizmente','categoria' => 'Adverb'),
  array('id' => '454','palavra' => 'Strangely','traducao' => 'Estranhamente','categoria' => 'Adverb'),
  array('id' => '455','palavra' => 'Perhaps','traducao' => 'Possivelmente','categoria' => 'Adverb'),
  array('id' => '456','palavra' => 'Obviously','traducao' => 'Obviamente','categoria' => 'Adverb'),
  array('id' => '457','palavra' => 'Amazingly','traducao' => 'Surpreendentemente ','categoria' => 'Adverb'),
  array('id' => '458','palavra' => 'Fortunately','traducao' => 'Felizmente','categoria' => 'Adverb'),
  array('id' => '459','palavra' => 'Easily','traducao' => 'Facilmente','categoria' => 'Adverb'),
  array('id' => '460','palavra' => 'Slowly','traducao' => 'Lentamente','categoria' => 'Adverb'),
  array('id' => '461','palavra' => 'Fast','traducao' => 'Rapidamente, Velozmente','categoria' => 'Adverb'),
  array('id' => '462','palavra' => 'Properly','traducao' => 'Devidamente','categoria' => 'Adverb'),
  array('id' => '463','palavra' => 'Carefully','traducao' => 'Cuidadosamente','categoria' => 'Adverb'),
  array('id' => '464','palavra' => 'Quietly','traducao' => 'Silenciosamente','categoria' => 'Adverb'),
  array('id' => '465','palavra' => 'Badly','traducao' => 'Seriamente','categoria' => 'Adverb'),
  array('id' => '466','palavra' => 'Well','traducao' => 'Satisfatoriamente, Bem, Vantajosamente','categoria' => 'Adverb'),
  array('id' => '467','palavra' => 'Here','traducao' => 'Aqui','categoria' => 'Adverb'),
  array('id' => '468','palavra' => 'There','traducao' => 'Lá','categoria' => 'Adverb'),
  array('id' => '469','palavra' => 'Away','traducao' => 'Longe, Distante','categoria' => 'Adverb'),
  array('id' => '470','palavra' => 'Out','traducao' => 'Fora','categoria' => 'Adverb'),
  array('id' => '471','palavra' => 'Inside','traducao' => 'Dentro','categoria' => 'Adverb'),
  array('id' => '472','palavra' => 'Upstairs','traducao' => 'Andar de cima','categoria' => 'Adverb'),
  array('id' => '473','palavra' => 'Far way','traducao' => 'Tão distante','categoria' => 'Adverb'),
  array('id' => '474','palavra' => 'Nearby','traducao' => 'Nas proximidades','categoria' => 'Adverb'),
  array('id' => '475','palavra' => 'Very','traducao' => 'Muito','categoria' => 'Adverb'),
  array('id' => '476','palavra' => 'Fairly','traducao' => 'Bastante, Justamente','categoria' => 'Adverb'),
  array('id' => '477','palavra' => 'Too','traducao' => 'Também','categoria' => 'Adverb'),
  array('id' => '478','palavra' => 'Quite','traducao' => 'Bastante','categoria' => 'Adverb'),
  array('id' => '479','palavra' => 'Extremely','traducao' => 'Extremamente','categoria' => 'Adverb'),
  array('id' => '480','palavra' => 'Absolutely','traducao' => 'Absolutamente','categoria' => 'Adverb'),
  array('id' => '481','palavra' => 'Incredibly','traducao' => 'Incrivelmente','categoria' => 'Adverb')
);
